### ISSUE TITLE
bundle exec rake results in an error

### ISSUE THREAD

**Issue by jasekiw** [ius-csg/csghomepage#21]
System: Windows 10

From the readme I wan `bundle exec rake` but it resulted in the following error
```
Traceback (most recent call last):
        2: from C:/tools/ruby25/bin/rake:31:in `<main>'
        1: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/rubygems_integration.rb:482:in `block in replace_bin_path'
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/rubygems_integration.rb:462:in `block in replace_bin_path': can't find executable rake for gem rake. rake is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::
Exception)
```

However when I ran:
`bundle exec jekyll build`

The site was generated without issue.

**Comment by TheOtherUnknown** [comment]
Trying running `bundle update` to ensure that Rake is installed. It was added to the Genfile recently.

**Comment by jasekiw** [comment]
@TheOtherUnknown Sorry, my HEAD on my local repo was out of date. Disregard this.
